### ISSUE TITLE
Is it possible to automate this?

### ISSUE THREAD

**Issue by elnath78** [LibreOffice/barcode#11]
Hi, Is it possible to have an A4 page containing more barcodes generated using macro? Or if the API allow it, is it possible using PHP?

**Comment by smehrbrodt** [comment]
Sure, see https://github.com/LibreOffice/barcode#api
Adjust the PositionX/PositionY parameters accordingly.

**Comment by elnath78** [comment]
@smehrbrodt 
Why it is not possible to record a macro? I tried to record a macro that adds a barcode but no code is being generated.

**Comment by smehrbrodt** [comment]
Because nobody implemented it yet.

**Comment by elnath78** [comment]
Is it complicate? Can I eventually make a fork and implement it or it will take too much time?

**Comment by smehrbrodt** [comment]
The macro recorder? That thing is in LibreOffice, you need to implement it there if you want to: https://www.libreoffice.org/community/developers/

**Comment by elnath78** [comment]
So it was not implemented in LibreOffice, I thought you were talking of the barcode plug-in.
