### ISSUE TITLE
Polish version

### ISSUE THREAD

**Issue by Jermor** [LibreOffice/barcode#4]
I prepared a Polish version for your project and adopted it on my computer.
I would like to pass it on to you for inclusion in the project.
By the way, I found a bug that prevented me from assigning a name to the "FrameControl1" field in the Barcode dialog". In Barcode.xdl, line 58 should look like this:
<dlg: title dlg: value = "& amp; 904.Barcode.FrameControl1.Label" />
For my purposes, I corrected the entry in the Barcode.py file by adding the "pl" symbol in line 24
To this post I attach the DialogStrings_pl_PL.properties file as txt format, with the Polish version of the messages and labels (see next post).

Good Job
.

**Comment by Jermor** [comment]
I found a few mistakes in the translation performed. Here I attach the corrected file.
[DialogStrings_pl_PL.txt](https://github.com/LibreOffice/barcode/files/7493185/DialogStrings_pl_PL.txt)

**Comment by smehrbrodt** [comment]
Thanks, new release with polish translation here: https://github.com/LibreOffice/barcode/releases/tag/v2.4.0
Also I fixed the untranslatable "Position" text in 4ee54f1ad585523d2233393696fd4620e00a0d57, thanks for the hint!

**Comment by Jermor** [comment]
Sorry, but there are four more problems:
The first is the wrong letter code, which I put in the DialogStrings_pl_PL.properties file. Its my mistake.
In heading 904 it should read:
904.Barcode.FrameControl1.Label=Po\u0142o\u017cenie

So \u017c instead of \u017a

Second. Due to the modification:
<dlg: title dlg: value = "& amp; 904.Barcode.FrameControl1.Label" />
In English language versions, there is text instead of the word Position, which I believe is about the idea of allowing multiple codes to be entered simultaneously. It begins with the words "Mass creation of barcode ...".

The third thing concerns the dialogue window. After hovering the mouse over the fields:
CODE128, PositionX or PositionY explanatory messages (in a tooltip) appear:
& 819.Barcode.CODE128.HelpText
& 922.Barcode.PositionX.HelpText
& 923.Barcode.Positiony.HelpText

The fourth is for alternate field selection with ALT + sign.
No abbreviation has been designated for the PositionX field. The letter Y has been designated for the PositionY field (it is underlined), but selecting ALT + Y moves the form factor to the PositionX field.
The same applies to the WidthModify and HeightModify fields. The former is assigned the letter W, but selecting ALT + W takes the user to the HeightModify field. The HeightModify field does not have a check mark assigned to it.

**Comment by Jermor** [comment]
Another thing. This applies to inserting a barcode via "Insert -> Object -> Barcode". For error messages generated by Barcode to appear in Polish, add the language code (pl) to the line of code in the Barcode.py file. As below.
SUPPORTED_LANGUAGES = ('en', 'da', 'de', 'fr', 'hu', 'ja', 'nl', 'pl', 'sh', 'sr', 'zh')    # first one is default

**Comment by smehrbrodt** [comment]
Thanks for all the testing.
Can you submit a pull request perhaps with your proposed changes?

**Comment by Jermor** [comment]
First, I must say that I don't know much about the GitHub platform. These are my first statements, so I'm quite clumsily navigating the app.
As for the proposed changes.
I posted the first ones above.

- I would suggest changing the WidthModify and HeightModify fields (in the Barcode dialog) from Combo to Numeric as for PositionX and PositionY.
Combo supports a text list, so it does not allow you to specify a minimum and maximum value. It allows you to enter any value, so if the user enters a value with a minus sign himself, he will receive a mirror image of the code with descriptions placed on the background of dashes. Therefore, it is not good for the size of the code to be arbitrary.
If the percentage ratio were to remain, it seems to me that the lower limit should be 10%. The upper one should also be set (e.g. 250%?).
I think that the user, when planning the code, wants to obtain a certain height of the bars, because it takes into account the way the code is read by the scanner. Maybe you could use the height of the bars in mm instead of the percentage of change in size. You can then allow a minimum value (e.g. 5 mm) and a maximum value (e.g. 150 mm).

- The Execute () method of the oJob object should return the body of the error message, or 0 when the process has completed without error, so that the programmer using the module can handle the event.

That's probably all my comments.
regards
