### ISSUE TITLE
Dialog different from readme and not allowing inclusion of digits

### ISSUE THREAD

**Issue by callegar** [LibreOffice/barcode#6]
I am trying the extension to produce barcodes and I don't understand if I am missing something or if there is some configuration of the extension to be done or if some features are only available "programmatically".

I would like to produce a barcode with numbers below it. From what I read this should be possible. However, the dialog does not provide any option in this regard. Furthermore, in my setup it looks different from what is shown by the readme in the github page (though consistent with the documentation provided by the help button).

Another aspect that I cannot seem to be able to configure is the top and bottom margin. In writer, the barcode is produced with a lot of empty space above and below it and the margin configuration option does not seem to affect it. In draw I can remove the margin by "breaking" the image corresponding to the barcode.

**Comment by smehrbrodt** [comment]
Which LibreOffice version are you using?
And can you share some screenshots describing the problem?

**Comment by callegar** [comment]
I am using 7.3 with version 2.4.0 of the extension (should be the latest) on linux.

When I do insert->object->barcode, I get this dialog:
![image](https://user-images.githubusercontent.com/1041166/154237316-4212176f-905a-4adb-9cd1-4ba0d9a9ea19.png)

I think that this may be a *native* dialog in my version of LibO that prevents the extension from providing its own Insert->Object->Barcode entry.

**Comment by callegar** [comment]
My bad, I uninstalled and reinstalled the extension again and now I see 2 barcode entries in the insert object menu, one from the extension and one native from LibO. The one with limited configurability and producing barcodes with weird margins is the native one.
