### ISSUE TITLE
Barcode Without Text

### ISSUE THREAD

**Issue by t4saha** [LibreOffice/barcode#7]
Create Barcode without Human readable text

**Comment by BoseSj** [comment]
Can you plz explain the issue here a bit more ellaborately?

**Comment by bjorn-l** [comment]
(Different user here, but with similar request.)

What I would like is the ability (a checkbox, perhaps) to specify no text under a barcode.  I am using Code 128.  I believe the text is added in function `add_text_above`.  Despite its name, the (Human-Readable) text is added under the barcode.

**Comment by BhattAbhilash** [comment]
Can you give us the framework and language to use in this for

**Comment by bjorn-l** [comment]
@BhattAbhilash
> Can you give us the framework and language to use in this for

Not sure what or who you are asking.  If you are asking about my case:  I use the Barcode extension in LibreOffice Writer.  (And it works in the other LibreOffice document types.)  I use the extension interactively through the graphical interface, inserting a Barcode object, not through the API.

**Comment by sgrobi** [comment]
Hi,
I have the same question. It is not an issue, but a feature request, I think.
When using this extension to generate barecode in a Libre Office Writer document, every generated barecode gets the "BarecodeValue" visible below the barcode image.
It would be nice to have an option to delete or hide this visible "BarecodeValue".

Any other suggestion is welcome.
Thank you!

**Comment by smehrbrodt** [comment]
Note that recent LibreOffice versions have its own barcode/QR Code generator.
There it's possible to generate a barcode without text.
All future development will happen in LibreOffice now.
